# Generated by Django 4.0.3 on 2022-03-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pesquisasAtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAAE', models.CharField(max_length=25)),
                ('TCLE', models.TextField()),
                ('TImagemVoz', models.TextField()),
                ('Profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='pacientesAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PacienteEscutou', models.BooleanField(default=False)),
                ('PacienteAutorizou', models.BooleanField(default=False)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.paciente')),
                ('Profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profissional')),
            ],
        ),
    ]
