# Generated by Django 4.0.3 on 2022-03-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientesativo',
            old_name='PacienteAutorizou',
            new_name='PacienteAutorizouImagem',
        ),
        migrations.AddField(
            model_name='pacientesativo',
            name='PacienteAutorizouPesquisa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacientesativo',
            name='PacienteAutorizouVideo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pacientesativo',
            name='PacienteAutorizouVoz',
            field=models.BooleanField(default=False),
        ),
    ]
